# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
